# <span style="color:red; font-size:30px"> Lecture 18b: Merging </span>

<font size = "4">

- Datasets are often spread across mutiple files.

- Multi-file datasets can be visualized with an "Entity Relationship Diagram" (ERD). 

- An ERD depicts how the identifiers in each table are connected.

- Here is an example ERD for 3 files in the Formula One dataset

<img src="f1_data/erd_f1_simple.png" alt="drawing" width="600"/>

- Let's examine this relationship in more detail

In [1]:
import pandas as pd

df_results = pd.read_csv("f1_data/results.csv")
df_races = pd.read_csv("f1_data/races.csv")
df_circuits = pd.read_csv("f1_data/circuits.csv")

In [2]:
print("df_results:")
display(df_results)
print("df_races:")
display(df_races)
print("df_circuits:")
display(df_circuits)

df_results:

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,25661,1086,825,210,20,13,16,16,16,0.0,69,\N,\N,37,15,1:23.511,188.856,11
25656,25662,1086,848,3,23,17,17,17,17,0.0,69,\N,\N,43,12,1:23.047,189.911,11
25657,25663,1086,849,3,6,19,18,18,18,0.0,69,\N,\N,60,8,1:22.478,191.221,11
25658,25664,1086,852,213,22,16,19,19,19,0.0,68,\N,\N,58,16,1:23.538,188.795,12
25659,25665,1086,822,51,77,8,20,20,20,0.0,65,\N,\N,60,19,1:24.002,187.752,131

df_races:

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074,1092,2022,18,22,Japanese Grand Prix,2022-10-09,05:00:00,http://en.wikipedia.org/wiki/2022_Japanese_Gra...,2022-10-07,04:00:00,2022-10-07,08:00:00,2022-10-08,04:00:00,2022-10-08,07:00:00,\N,\N
1075,1093,2022,19,69,United States Grand Prix,2022-10-23,19:00:00,http://en.wikipedia.org/wiki/2022_United_State...,2022-10-21,19:00:00,2022-10-21,22:00:00,2022-10-22,19:00:00,2022-10-22,22:00:00,\N,\N
1076,1094,2022,20,32,Mexico City Grand Prix,2022-10-30,20:00:00,http://en.wikipedia.org/wiki/2022_Mexican_Gran...,2022-10-28,18:00:00,2022-10-28,21:00:00,2022-10-29,17:00:00,2022-10-29,20:00:00,\N,\N
1077,1095,2022,21,18,Brazilian Grand Prix,2022-11-13,18:00:00,http://en.wikipedia.org/wiki/2022_Brazilian_Gr...,2022-11-11,15:30:00,2022-11-12,15:30:00,\N,\N,2022-11-11,19:00:00,2022-11-12,19:30:00
1078,1096,2022,22,24,Abu Dhabi Grand Prix,2022-11-20,13:00:00,http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...,2022-11-18,09:00:00,2022-11-18,12:00:00,2022-11-19,10:00:00,2022-11-19,13:00:00,\N,\N

df_circuits:

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park
...,...,...,...,...,...,...,...,...,...
71,75,portimao,Autódromo Internacional do Algarve,Portimão,Portugal,37.22700,-8.62670,108,http://en.wikipedia.org/wiki/Algarve_Internati...
72,76,mugello,Autodromo Internazionale del Mugello,Mugello,Italy,43.99750,11.37190,255,http://en.wikipedia.org/wiki/Mugello_Circuit
73,77,jeddah,Jeddah Corniche Circuit,Jeddah,Saudi Arabia,21.63190,39.10440,15,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
74,78,losail,Losail International Circuit,Al Daayen,Qatar,25.49000,51.45420,\N,http://en.wikipedia.org/wiki/Losail_Internatio...
75,79,miami,Miami International Autodrome,Miami,USA,25.95810,-80.23890,\N,http://en.wikipedia.org/wiki/Miami_Internation...

<font size = "4">

- We can use these 3 separate data frames together to gain information about a race result.

In [3]:
# pick one of the rows in results.csv between 0 and 25,659

result_row = 25
# result_row = 3000
# result_row = 24001
race_result = df_results.iloc[result_row, :]

print("race_result:", result_row)

# grab the raceId number
race_id = race_result["raceId"]
print("race ID:", race_id)

# use the raceId number to grab the corresponding row of the races.csv dataset
race_info = df_races.query("raceId == @race_id")

race_year = race_info["year"].item()
race_name = race_info["name"].item()
circuit_id = race_info["circuitId"].item()

print("Year:", race_year)
print("Name of Race:", race_name)

# use circuitId number to grab the corresponding row of the circuits.csv dataset
circuit_info = df_circuits.query("circuitId == @circuit_id")
circuit_name = circuit_info["name"].item()
circuit_loc = circuit_info["location"].item()
circuit_country = circuit_info["country"].item()

print("Circuit Name:", circuit_name)
print("Location:", circuit_loc)
print("Country:", circuit_country)

race_result: 25
race ID: 19
Year: 2008
Name of Race: Malaysian Grand Prix
Circuit Name: Sepang International Circuit
Location: Kuala Lumpur
Country: Malaysia

<font size = "4">

- Navigating between 3 different DataFrames is not ideal. 

- It would be nice if we could combine the DataFrames in some way.

- We can't "stack" them together (called concatenation) because the first DataFrame has 25,660 rows, the second has 1,079 rows, and the third only has 76 rows.

- However, we can "merge" them together using the Pandas function `pd.merge`

- We'll begin by working with some smaller DataFrames just for visualization's sake

In [ ]:
results_short = df_results[["resultId", "raceId", "driverId", "points"]]
races_short = df_races[["raceId", "year", "circuitId", "name"]]
circuits_short = df_circuits[["circuitId", "name", "location", "country"]]

print("results_short:")
display(results_short)
print("races_short:")
display(races_short)
print("circuits_short:")
display(circuits_short)

<font size = "4">

- We will combine `results_short` and `races_short` in the following way.

- Here are rows 0, 23, and 46 of `results_short` (you can get them using .iloc)


<div align="center">

|  | resultId | raceId | driverId | points |
| -------- | -------- | -------- | -------- | -------- |
| 0   | 1  | 18 | 1 | 10 |
| 23   | 24  | 19 | 9 | 8 |
| 46   | 47  | 20 | 9 | 6 |

</div>

- Here are rows 17, 18, and 19 of `races_short` (again, use .iloc)

<div align="center">

|  | raceId | year | circuitId | name |
| -------- | -------- | -------- | -------- | -------- |
| 17   | 18  | 2008 | 1 | Australian Grand Prix |
| 18   | 19  | 2008 | 2 | Malaysian Grand Prix |
| 19   | 20  | 2008 | 3 | Bahrain Grand Prix |

</div>

- After we use `pd.merge` to create a new DataFrame called `df_merged`, rows 0, 23, and 46 of the new DataFrame will be:

<div align="center">

|  | resultId | raceId | driverId | points | year | circuitId | name |
| -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- |
| 0   | 1  | 18 | 1 | 10 | 2008 | 1 | Australian Grand Prix | 
| 23   | 24  | 19 | 9 | 8 | 2008 | 2 | Malaysian Grand Prix |
| 46   | 47  | 20 | 9 | 6 | 2008 | 3 | Bahrain Grand Prix |

</div>

In [ ]:
df_merged = pd.merge(left = results_short, right = races_short, how = "left", on = "raceId")

display(df_merged)
print()
display(df_merged.iloc[[0, 23, 46], :])

<font size = "4">

- We used 4 keyword arguments in `pd.merge`

- "left" and "right" are the two DataFrames we are merging. The choice of which one is "left" and which one is "right" will affect the ultimate order of the columns in the merged DataFrame.

- "how" is a string that describes how the merge is performed. For this class, we will just focus on "left" and "right". (Other advanced choices include "outer", "inner", "cross", "left_anti", "right_anti")

- When we do `how = "left"`, we are basically treating the "left" DataFrame as the primary one. The order of the rows is chosen to maintain the order of the data in the left DataFrame.

- "on" is a string corresponding to the merging variable. In this case we are merging based on "raceId". Rows in the two datasets with identical values of raceId are matched, and the additional info from the "right" DataFrame is added on to the "left" DataFrame.

<font size = "4">

**Exercise:** Run the following cell and print/display the outputs to see how the merging procedure works for other choices of "left", "right", and "how".

In [ ]:
df_merged_2 = pd.merge(left = results_short, right = races_short, how = "right", on = "raceId")

df_merged_3 = pd.merge(left = races_short, right = results_short, how = "left", on = "raceId")

df_merged_4 = pd.merge(left = races_short, right = results_short, how = "right", on = "raceId")

<font size = "4">

- Next, we perform an additional merge so that we include the data from `circuits_short`

In [ ]:
df_merged_final = pd.merge(left = df_merged, right = circuits_short, how = "left", on = "circuitId")

display(df_merged_final.head())

<font size = "4">

<font size = "4">

Do you notice anything odd about the column names?

<font size = "4">

Instead of creating the additional variables `results_short`, `races_short`, and `circuits_short` we could have directly subsetted the desired columns when passing in the input arguments to `pd.merge`.